# Generated by Django 3.0.10 on 2020-12-12 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_offer_coutrycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBookingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingclass', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='coutrycode',
        ),
        migrations.AlterField(
            model_name='offer',
            name='bookingclass',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.OfferBookingClass'),
        ),
    ]
