# Generated by Django 3.0.10 on 2020-12-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20201212_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='bookingclass',
            field=models.CharField(max_length=4),
        ),
        migrations.DeleteModel(
            name='OfferBookingClass',
        ),
    ]
