# Generated by Django 3.1.2 on 2020-10-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station', models.CharField(max_length=120)),
                ('Pickupdate', models.DateField()),
                ('Pickuptimestart', models.TimeField()),
                ('Pickuptimeend', models.TimeField()),
                ('Dropoffdate', models.DateField()),
                ('Dropofftimestart', models.TimeField()),
                ('Dropofftimeend', models.TimeField()),
            ],
        ),
    ]
