# Generated by Django 3.1.2 on 2020-11-05 14:37

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20201023_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarType', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=10)),
                ('PickUpDate', models.DateField()),
                ('PickUpTime', models.TimeField()),
                ('DropOffDate', models.DateField()),
                ('DropOffTime', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='searchinput',
            name='Dropoffdate',
            field=models.DateField(verbose_name='Drop-off Date'),
        ),
        migrations.AlterField(
            model_name='searchinput',
            name='Dropofftimeend',
            field=models.TimeField(help_text='<br>Please be aware, that latest drop-off time should be <strong>no later than 2 hours</strong> after first drop-off time.', verbose_name='Latest Drop-Off time'),
        ),
        migrations.AlterField(
            model_name='searchinput',
            name='Dropofftimestart',
            field=models.TimeField(verbose_name='Earliest Drop-off time'),
        ),
        migrations.AlterField(
            model_name='searchinput',
            name='Pickupdate',
            field=models.DateField(validators=[frontend.models.no_past], verbose_name='Pick-up Date'),
        ),
        migrations.AlterField(
            model_name='searchinput',
            name='Pickuptimeend',
            field=models.TimeField(help_text='<br>Please be aware, that latest pick-up time should be <strong>no later than 2 hours</strong> after first pick-up time.', verbose_name='Latest Pick-Up time'),
        ),
        migrations.AlterField(
            model_name='searchinput',
            name='Pickuptimestart',
            field=models.TimeField(verbose_name='Earliest Pick-Up time'),
        ),
        migrations.AlterField(
            model_name='searchinput',
            name='Station',
            field=models.CharField(max_length=120, verbose_name='Rental station'),
        ),
    ]
