# Generated by Django 3.1.2 on 2020-11-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20201118_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerlist',
            options={'managed': False},
        ),
    ]
