# Generated by Django 3.1.2 on 2020-11-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20201118_1905'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='offerlist',
            table='allresults',
        ),
    ]
