# Generated by Django 3.1.2 on 2020-11-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20201118_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartype', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('pickupdate', models.DateField()),
                ('pickuptime', models.TimeField()),
                ('dropoffdate', models.DateField()),
                ('dropofftime', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='OfferList',
        ),
    ]
