# Generated by Django 3.1.2 on 2020-11-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20201119_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='dropoffdate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pickupdate',
            field=models.CharField(max_length=10),
        ),
    ]
