# Generated by Django 3.1.2 on 2020-11-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20201120_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='cardescription',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
