# Generated by Django 3.1.2 on 2020-11-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_offer_cardescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchinput',
            name='Dropofftimeend',
            field=models.TimeField(default='08:00:00', help_text='<br>Please be aware, that latest drop-off time should be <strong>no later than 2 hours</strong> after first drop-off time.', verbose_name='Latest Drop-Off time'),
        ),
        migrations.AlterField(
            model_name='searchinput',
            name='Dropofftimestart',
            field=models.TimeField(verbose_name='Drop-off time'),
        ),
        migrations.AlterField(
            model_name='searchinput',
            name='Pickuptimeend',
            field=models.TimeField(default='08:00:00', help_text='<br>Please be aware, that latest pick-up time should be <strong>no later than 2 hours</strong> after first pick-up time.', verbose_name='Latest Pick-Up time'),
        ),
        migrations.AlterField(
            model_name='searchinput',
            name='Pickuptimestart',
            field=models.TimeField(verbose_name='Pick-Up time'),
        ),
    ]
