# Generated by Django 3.0.10 on 2020-11-27 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_offer_searchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='coutrycode',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
