# Generated by Django 3.0.10 on 2021-04-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20210401_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='dropofftimes',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='pickuptimes',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
