# Generated by Django 3.0.10 on 2021-04-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20210401_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='dropofftimes',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pickuptimes',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
